//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Auto Order
{
	private int MinStockAllowed
	{
		get;
		set;
	}

	private int maxStockAllowed
	{
		get;
		set;
	}

	private int critical
	{
		get;
		set;
	}

	private int currentStock
	{
		get;
		set;
	}

	private int productCode
	{
		get;
		set;
	}

	public virtual void CreateOrder()
	{
		throw new System.NotImplementedException();
	}

}

