//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

public class DBConnection
{
    public const string CONNECTION_STRING = "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=c:\\database\\Inventory.mdf;Integrated Security=True;Connect Timeout=30";


    public virtual string connString
	{
		get;
		set;
	}

	public virtual void add()
	{
		throw new System.NotImplementedException();
	}

    public void Delete(string tableName, string fieldName, int pkValue)
    {
        using (SqlConnection conn = new SqlConnection())
        {
            conn.ConnectionString = DBConnection.CONNECTION_STRING;
            conn.Open();

            String sql;
            sql = "delete from [" + tableName + "] where [" + fieldName + "] = @id";

            SqlCommand command = new SqlCommand(sql, conn);
            command.Parameters.AddWithValue("id", pkValue);

            command.ExecuteNonQuery();
        }
    }

    public virtual void search()
	{
		throw new System.NotImplementedException();
	}

	public virtual void save()
	{
		throw new System.NotImplementedException();
	}

}

