//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DBConnection
{
	public virtual string connString
	{
		get;
		set;
	}

	public virtual void add()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete()
	{
		throw new System.NotImplementedException();
	}

	public virtual void search()
	{
		throw new System.NotImplementedException();
	}

	public virtual void save()
	{
		throw new System.NotImplementedException();
	}

}

