//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

public class DBConnection
{
    public const string CONNECTION_STRING = "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=c:\\database\\Inventory.mdf;Integrated Security=True;Connect Timeout=30";


    public virtual string connString
	{
		get;
		set;
	}

	public virtual void add()
	{
		throw new System.NotImplementedException();
	}

    public void Delete(string tableName, string fieldName, int pkValue)
    {
        using (SqlConnection conn = new SqlConnection())
        {
            conn.ConnectionString = DBConnection.CONNECTION_STRING;
            conn.Open();

            String sql;
            sql = "delete from [" + tableName + "] where [" + fieldName + "] = @id";

            SqlCommand command = new SqlCommand(sql, conn);
            command.Parameters.AddWithValue("id", pkValue);

            command.ExecuteNonQuery();
        }
    }
    public static Employee get(string userName,string passwd)
    {
        using (SqlConnection conn = new SqlConnection())
        {
            conn.ConnectionString = CONNECTION_STRING;
            conn.Open();

            String sql;
            sql = "select employee_id, first_name, last_name, username , encrypted_password from Employee where username = @id";

            SqlCommand command = new SqlCommand(sql, conn);
            command.Parameters.AddWithValue("id", userName);

            using (SqlDataReader read = command.ExecuteReader())
            {
                if (read.HasRows)
                {
                    read.Read();
                    Employee a = new Employee(
                        read.GetInt32(0),
                        read.GetString(1),
                         read.GetString(2),
                          read.GetString(3),
                           read.GetString(4)
                         );
                    a.Print();
                    Console.WriteLine("Decrypt password");
                    Console.WriteLine(Employee.Decrypt(Employee.getPass(a)));
                    return a;
                }
                else
                {
                    return null;
                }
           
            }
        }
    }


    public virtual void search()
	{
		throw new System.NotImplementedException();
	}

	public virtual void save()
	{
		throw new System.NotImplementedException();
	}

}

