//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

public class Employee : DBConnection
{
	private string firstName
	{
		get;
		set;
	}

	private string lastName
	{
		get;
		set;
	}

	private int employeeId
	{
		get;
		set;
	}

	private string passWord
	{
		get;
		set;
	}

	private string userName
	{
		get;
		set;
	}

    /*
	public virtual Login Login
	{
		get;
		set;
	}*/

    public Employee()
    {

    }

	public Employee(string fn, string ln, string employeeCode, string pasword)
	{
        this.firstName = fn;
        this.lastName = ln;
        this.employeeId = -1;
        this.userName = employeeCode;
        passWord = pasword;
	}

	public void Print()
	{
        Console.WriteLine(firstName);
        Console.WriteLine(lastName);
        Console.WriteLine(employeeId);
        Console.WriteLine(userName);
        Console.WriteLine(passWord);
    }
    public override string ToString()
    {
        string printString;
        printString = "" + firstName + " " + lastName + " " + employeeId + " " + userName + " " + passWord;
        return printString; 
    }

    public virtual void verifyPassword(string passWd)
	{
		throw new System.NotImplementedException();
	}
    public virtual void addEmployeeToDB()
    {
        using (SqlConnection conn = new SqlConnection())
        {
            conn.ConnectionString = DBConnection.CONNECTION_STRING;
            conn.Open();

            string sql;

            if (employeeId == -1)
            {
                //Employee (names in DB  )      Values(names in DB) 
                sql = "INSERT INTO Employee(first_name,last_name,username,encrypted_password) VALUES(@first_name,@last_name,@username,@encrypted_password)"
                    + "SELECT CAST (scope_identity() as int)";
            }
            else
            {
                // sql = "UPDATE Employee set Status_Text = @Status_Text where OrderStatus_Id = @OrderStatus_Id";
                 sql = "UPDATE Employee set first_name = @first_name where employee_id = @employeeId";

            }

            SqlCommand command = new SqlCommand(sql, conn);
            command.Parameters.AddWithValue("first_name", firstName);
            command.Parameters.AddWithValue("last_name", lastName);
            command.Parameters.AddWithValue("username", userName);
            command.Parameters.AddWithValue("encrypted_password", passWord);

            if (employeeId == -1)
            {
                employeeId = (int)command.ExecuteScalar();
            }


        }
    }

}

