//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Login
{
	private string userName
	{
		get;
		set;
	}

	private string passWord
	{
		get;
		set;
	}

	private int employeeCODE
	{
		get;
		set;
	}

	private void VerifyPassword(string fn, string ln, int id, int employeeCode)
	{
		throw new System.NotImplementedException();
	}

	private void CreatePassword()
	{
		throw new System.NotImplementedException();
	}

}

