//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OrderProcessing
{
    public string fileName { get; private set; }

	public virtual void getOrder(string file)
	{
		throw new System.NotImplementedException();
	}

	public virtual void applyFiltersToOrder()
	{
		throw new System.NotImplementedException();
	}

	public virtual void createOrder()
	{
		throw new System.NotImplementedException();
	}

    public override string ToString()
    {
		throw new System.NotImplementedException();
	}

}

