//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

public class OrderStatus 
{
	public string Status_Text    { get; private set; }
    public int    OrderStatus_Id { get; private set; }

    public OrderStatus(string statusText)
    {
        this.OrderStatus_Id = -1;
        this.Status_Text = statusText;
    }

    private OrderStatus(int OrderStatus_Id, string Status_Text)
    {
        this.OrderStatus_Id = OrderStatus_Id;
        this.Status_Text = Status_Text;
    }


	public static List<OrderStatus> GetAll()
    {
        using (SqlConnection conn = new SqlConnection())
        {
            conn.ConnectionString = DBConnection.CONNECTION_STRING;
            conn.Open();

            string sql = "SELECT OrderStatus_Id, Status_Text "
                       + "FROM OrderStatus ";

            SqlCommand command = new SqlCommand(sql, conn);
            using (SqlDataReader reader = command.ExecuteReader())
            {
                List<OrderStatus> statusList = new List<OrderStatus>();

                while (reader.Read())
                {
                    OrderStatus status = new OrderStatus(reader.GetInt32(0),
                                                         reader.GetString(1));
                    statusList.Add(status);
                }

                return statusList;
            }
        }
    }

    public override string ToString()
    {
        return this.Status_Text;
    }

}

