//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Orders : DBConnection
{
	private int orderId
	{
		get;
		set;
	}

	private string orderDate
	{
		get;
		set;
	}

	private string employee
	{
		get;
		set;
	}

	private string shippingAddress
	{
		get;
		set;
	}

	private string shipCity
	{
		get;
		set;
	}

	private string shipState
	{
		get;
		set;
	}

	private int zip
	{
		get;
		set;
	}

	private Double orderTota
	{
		get;
		set;
	}

	private string status
	{
		get;
		set;
	}

	private string closedDate
	{
		get;
		set;
	}

	public override string ToString()
	{
		throw new System.NotImplementedException();
	}

}

