//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

public class OrderDetails : DBConnection
{
    public int    OrderDetails_Id { get; private set; }
    public int    Order_Id        { get; private set; }
    public string Product         { get; private set; }
    public int    Quantity        { get; private set; }
    public Double Unit_Price      { get; private set; }
    public Double Extended_Price  { get; private set; }
    public string Status          { get; private set; }

    public OrderDetails(int Order_Id, string Product, int Quantity, double Unit_Price, double Extended_Price, string Status)
    {
        this.Order_Id       = Order_Id;
        this.Product        = Product;
        this.Quantity       = Quantity;
        this.Unit_Price     = Unit_Price;
        this.Extended_Price = Extended_Price;
        this.Status         = Status;
        OrderDetails_Id     = -1;
    }

    private OrderDetails(int OrderDetails_Id, int Order_Id, string Product, int Quantity, double Unit_Price, double Extended_Price, string Status)
    {
        this.OrderDetails_Id = OrderDetails_Id;
        this.Order_Id        = Order_Id;
        this.Product         = Product;
        this.Quantity        = Quantity;
        this.Unit_Price      = Unit_Price;
        this.Extended_Price  = Extended_Price;
        this.Status          = Status;
    }


    public void Save()
    {
        using (SqlConnection conn = new SqlConnection())
        {
            conn.ConnectionString = DBConnection.CONNECTION_STRING;
            conn.Open();

            string sql;

            if (OrderDetails_Id == -1)
            {
                sql = "INSERT INTO OrderDetails(Order_Id, Product, Quantity, Unit_Price, Extended_Price, Status) "
                    + "VALUES(@Order_Id, @Product, @Quantity, @Unit_Price, @Extended_Price, @Status) "
                    + "SELECT CAST (scope_identity() as int)";
            }
            else
            {
                sql = "UPDATE OrderDetails SET "
                    + "Order_Id = @Order_Id, Product = @Product, Quantity = @Quantity, Unit_Price = @Unit_Price, Extended_Price = @Extended_Price, Status = @Status "
                    + "WHERE OrderDetails_Id = @OrderDetails_Id";
            }

            SqlCommand command = new SqlCommand(sql, conn);

            command.Parameters.AddWithValue("Order_Id", Order_Id);
            command.Parameters.AddWithValue("Product", Product);
            command.Parameters.AddWithValue("Quantity", Quantity);
            command.Parameters.AddWithValue("Unit_Price", Unit_Price);
            command.Parameters.AddWithValue("Extended_Price", Extended_Price);
            command.Parameters.AddWithValue("Status", Status);

            if (OrderDetails_Id == -1)
            {
                OrderDetails_Id = (int)command.ExecuteScalar();
            }
            else
            {
                command.Parameters.AddWithValue("OrderDetails_Id", OrderDetails_Id);
                command.ExecuteNonQuery();
            }
        }
    }


    public static OrderDetails Get(int OrderDetails_Id)
    {
        using (SqlConnection conn = new SqlConnection())
        {
            conn.ConnectionString = DBConnection.CONNECTION_STRING;
            conn.Open();
            
            string sql = "SELECT OrderDetails_Id, Order_Id, Product, Quantity, Unit_Price, Extended_Price, Status "
                       + "FROM OrderDetails "
                       + "WHERE OrderDetails_Id = @OrderDetails_Id";

            SqlCommand command = new SqlCommand(sql, conn);
            command.Parameters.AddWithValue("OrderDetails_Id", OrderDetails_Id);

            using (SqlDataReader reader = command.ExecuteReader())
            {
                if (reader.HasRows)
                {
                    reader.Read();

                    OrderDetails od = new OrderDetails(reader.GetInt32(0),
                                                       reader.GetInt32(1),
                                                       reader.GetString(2),
                                                       reader.GetInt32(3),
                                                       reader.GetDouble(4),
                                                       reader.GetDouble(5),
                                                       reader.GetString(5));
                    return od;
                }
                else
                {
                    return null;
                }
            }
        }
    }


    public static List<OrderDetails> GetAll()
    {
        using (SqlConnection conn = new SqlConnection())
        {
            conn.ConnectionString = DBConnection.CONNECTION_STRING;
            conn.Open();

            string sql = "SELECT OrderDetails_Id, Order_Id, Product, Quantity, Unit_Price, Extended_Price, Status "
                       + "FROM OrderDetails ";

            SqlCommand command = new SqlCommand(sql, conn);
            using (SqlDataReader reader = command.ExecuteReader())
            {
                List<OrderDetails> OrderDetailsList = new List<OrderDetails>();

                while (reader.Read())
                {
                    OrderDetails od = new OrderDetails(reader.GetInt32(0),
                                                       reader.GetInt32(1),
                                                       reader.GetString(2),
                                                       reader.GetInt32(3),
                                                       reader.GetDouble(4),
                                                       reader.GetDouble(5),
                                                       reader.GetString(5));

                    OrderDetailsList.Add(od);
                }

                return OrderDetailsList;
            }
        }
    }


    public override string ToString()
    {
		throw new System.NotImplementedException();
	}

}

