//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Order Details : DBConnection
{
	private int orderDetailsId
	{
		get;
		set;
	}

	private int orderID
	{
		get;
		set;
	}

	private string Product
	{
		get;
		set;
	}

	private int quantity
	{
		get;
		set;
	}

	private Double unitPrice
	{
		get;
		set;
	}

	private Double extendedPrice
	{
		get;
		set;
	}

	private string statue
	{
		get;
		set;
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

}

