//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Product : DBConnection
{
	private string Product_Name { get; set; }
	private string Product_Code { get; set; }
	private bool Discontine { get; set; }
	private string Category { get; set; }
	private int Product_Id { get; set; }
	private Double List_Price { get; set; }
	private Double Unit_Cost { get; set; }



	public override string ToString()
	{
		throw new System.NotImplementedException();
	}

	public Product(string productName, string productCode, string category, double listPrice, double unitCost)
	{
        this.Product_Name = productName;
        this.Product_Code = productCode;

	}

}

