//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PurchaseOrderDetails : DBConnection
{
	private int purchaseOrderDetailId
	{
		get;
		set;
	}

	private int purchaseOrderNumber
	{
		get;
		set;
	}

	private string product
	{
		get;
		set;
	}

	private int quanity
	{
		get;
		set;
	}

	private Double unitPrice
	{
		get;
		set;
	}

	private Double extendedPrice
	{
		get;
		set;
	}

	private string dateReceived
	{
		get;
		set;
	}

	private string status
	{
		get;
		set;
	}

    public override string ToString()
    {
		throw new System.NotImplementedException();
	}

}

