//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PurchaseOrder : DBConnection
{
	private int purchaseOrderDetailId
	{
		get;
		set;
	}

	private string orderDate
	{
		get;
		set;
	}

	private string createdBy
	{
		get;
		set;
	}

	private string createdDate
	{
		get;
		set;
	}

	private Double shippingFees
	{
		get;
		set;
	}

	private Double taxes
	{
		get;
		set;
	}

	private string paymentDate
	{
		get;
		set;
	}

	private Double paymentAmount
	{
		get;
		set;
	}

	private Double orderTotal
	{
		get;
		set;
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

}

