//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PurchaseOrderDetails : DBConnection
{
	private int    PurchaseOrderDetails_Id { get; set; }
	private int    Purchase_Order_Number  { get; set; }
	private string Product                { get; set; }
	private int    Quantity               { get; set; } 
	private Double Unit_Price             { get; set; }
	private Double Extended_Price         { get; set; }
	private string Date_Received          { get; set; }
	private string Status                 { get; set; }


    public PurchaseOrderDetails(int Purchase_Order_Number, string Product, int Quantity, double Unit_Price, double Extended_Price, string Date_Received, string Status)
    {
        this.PurchaseOrderDetails_Id = -1;
        this.Purchase_Order_Number = Purchase_Order_Number;

    }


    public override string ToString()
    {
		throw new System.NotImplementedException();
	}

}

