SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (6, N'CR001', N'Ravioli   ', 14.63, 19.5, 0, N'Pasta')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (7, N'CR002', N'Spaghetti ', 4.55, 8.99, 0, N'Pasta')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (8, N'CR003', N'Macaroni  ', 1.55, 4.55, 0, N'Pasta')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (9, N'BG001', N'Flour     ', 2.55, 3.99, 0, N'Baking')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (10, N'BG002', N'Sugar     ', 0.55, 2.99, 0, N'Baking')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (14, N'BG003', N'Vanilla Extract', 0.33, 1.55, 0, N'Baking')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (15, N'BG004', N'Baking Powder', 0.55, 2.99, 0, N'Baking')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (16, N'BD001', N'Dr.Pepsi', 0.55, 1.99, 0, N'Beverages')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (17, N'BD002', N'Nuka Cola', 0.55, 1.99, 0, N'Beverages')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (19, N'CD001', N'Reese''s', 0.25, 0.99, 0, N'Candy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (20, N'CD002', N'Smarties', 0.1, 0.55, 0, N'Candy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (22, N'CD003', N'Air Heads', 0.15, 0.55, 0, N'Candy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (23, N'4011', N'Banana', 0.1, 0.55, 0, N'Produce')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (24, N'4133', N'Apple', 0.15, 0.99, 0, N'Produce')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (25, N'4022', N'Grapes', 0.65, 1.55, 0, N'Produce')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (26, N'4028', N'Strawberries', 0.42, 0.99, 0, N'Produce')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (27, N'MD001', N'Steak', 0.78, 5.99, 0, N'Meat')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (28, N'MD002', N'Pork', 0.98, 3.56, 0, N'Meat')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (29, N'MD003', N'Chicken Thighs', 1.55, 3.55, 0, N'Meat')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (30, N'CB001', N'Admiral Crunch', 0.45, 1.99, 0, N'Cereal')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (31, N'CB002', N'Fruity Puffs', 0.45, 1.99, 0, N'Cereal')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (32, N'CB003', N'Tricks', 0.45, 1.99, 0, N'Cereal')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (33, N'CS001', N'Dorito''s', 0.46, 2.55, 0, N'Chips')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (34, N'CS002', N'Nacho''s', 0.25, 1.99, 0, N'Chips')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (35, N'CM001', N'Ketchup', 0.33, 0.99, 0, N'Condiments')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (36, N'CM002', N'Mustard', 0.38, 0.99, 0, N'Condiments')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (37, N'CM003', N'Ranch', 0.12, 0.99, 0, N'Condiments')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (38, N'DA001', N'Milk 2%', 0.15, 1.55, 0, N'Dairy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (40, N'DA002', N'Milk 1%', 0.15, 1.55, 0, N'Dairy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (41, N'DA003', N'Milk Skim', 0.15, 1.55, 0, N'Dairy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (42, N'DA004', N'Milk Whole', 0.15, 1.55, 0, N'Dairy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (43, N'SP001', N'Ramen', 0.05, 0.55, 0, N'Soups')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (44, N'SP002', N'Chicken Noodle Soup', 0.25, 0.75, 0, N'Soups')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (45, N'OL001', N'Olive Oil', 0.15, 1.99, 0, N'Oils')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (46, N'DA005', N'Eggs', 0.55, 1.89, 0, N'Dairy')
SET IDENTITY_INSERT [dbo].[Product] OFF
