SET IDENTITY_INSERT [dbo].[Category] ON
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (2, N'Baking')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (3, N'Beverages')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (4, N'Candy')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (5, N'Canned Fruit and Vegetables')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (6, N'Canned Meat')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (7, N'Cereal')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (8, N'Chips')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (9, N'Condiments')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (10, N'Dairy')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (11, N'Pasta')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (12, N'Snacks')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (13, N'Soups')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (14, N'Oils')
SET IDENTITY_INSERT [dbo].[Category] OFF
