
SET IDENTITY_INSERT [dbo].[Category] ON
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (2, N'Baking')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (3, N'Beverages')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (4, N'Candy')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (5, N'Canned Fruit and Vegetables')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (6, N'Canned Meat')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (7, N'Cereal')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (8, N'Chips')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (9, N'Condiments')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (10, N'Dairy')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (11, N'Pasta')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (12, N'Snacks')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (13, N'Soups')
INSERT INTO [dbo].[Category] ([Category_Id], [Category_Text]) VALUES (14, N'Oils')
SET IDENTITY_INSERT [dbo].[Category] OFF

SET IDENTITY_INSERT [dbo].[Employee] ON
INSERT INTO [dbo].[Employee] ([employee_id], [first_name], [last_name], [username], [encrypted_password]) VALUES (1, N'First Name', N'Last Name', N'User Name ', N'Password')
INSERT INTO [dbo].[Employee] ([employee_id], [first_name], [last_name], [username], [encrypted_password]) VALUES (2, N'Sam', N'Smith', N'@smith    ', N'lFhHTtUwkNZ1Q7kL/qBO6w==')
INSERT INTO [dbo].[Employee] ([employee_id], [first_name], [last_name], [username], [encrypted_password]) VALUES (3, N'test_UserFN', N'test_UserLN', N'@test_User', N'240u0HKuQlMH2bEJymBRwg==')
SET IDENTITY_INSERT [dbo].[Employee] OFF

SET IDENTITY_INSERT [dbo].[Inventory] ON
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (1, N'CR001', N'Ravioli', N'A101', 10, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (2, N'CR002', N'Spaghetti', N'A102', 10, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (3, N'CR003', N'Macaroni', N'A103', 10, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (4, N'BG001', N'Flour', N'A104', 15, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (5, N'BG002', N'Sugar', N'A105', 15, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (6, N'BG003', N'Vanilla Extract', N'A106', 15, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (7, N'BG004', N'Baking Powder', N'A107', 15, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (8, N'BD001', N'Dr.Pepsi', N'A108', 10, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (9, N'BD002', N'Nuka Cola', N'A109', 10, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (10, N'CD001', N'Reese''s', N'A110', 10, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (11, N'CD002', N'Smarties', N'A111', 10, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (13, N'CD003', N'Air Heads', N'A112', 10, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (14, N'4011', N'Banana', N'A120', 50, 15, 15, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (15, N'4133', N'Apple', N'A121', 50, 15, 15, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (16, N'4022', N'Grapes', N'A122', 50, 15, 15, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (17, N'4028', N'Strawberries', N'A123', 50, 15, 15, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (18, N'MD001', N'Steak', N'A130', 15, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (19, N'MD002', N'Pork', N'A131', 25, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (20, N'MD003', N'Chicken Thighs', N'A132', 25, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (21, N'CB001', N'Admiral Crunch', N'A140', 20, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (22, N'CB002', N'Fruity Puffs', N'A141', 20, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (23, N'CB003', N'Tricks', N'A142', 20, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (24, N'CS001', N'Dorito''s', N'A150', 15, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (25, N'CS002', N'Nacho''s', N'A151', 15, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (26, N'CM001', N'Ketchup', N'A160', 10, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (27, N'CM002', N'Mustard', N'A161', 10, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (28, N'CM003', N'Ranch', N'A162', 10, 3, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (29, N'DA001', N'Milk 2%', N'A170', 20, 5, 5, 20)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (30, N'DA002', N'Milk 1%', N'A171', 20, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (31, N'DA003', N'Milk Skim', N'A172', 20, 5, 5, 20)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (32, N'DA004', N'Millk Whole', N'A173', 20, 5, 3, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (33, N'DA005', N'Eggs', N'A174', 50, 30, 10, 40)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (34, N'SP001', N'Ramen', N'A180', 25, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (35, N'SP002', N'Chicken Noodle Soup', N'A181', 25, 5, 5, 0)
INSERT INTO [dbo].[Inventory] ([Inventory_Id], [Product_Code], [Product], [Product_Location], [On_Hand], [Reorder_Level], [Reorder_Quantity], [On_Order]) VALUES (36, N'OL001', N'Olive Oil', N'A182', 10, 5, 5, 0)
SET IDENTITY_INSERT [dbo].[Inventory] OFF

INSERT INTO [dbo].[OrderDetails] ([OrderDetails_Id], [Order_Id], [Product], [Quantity], [Unit_Price], [Extended_Price]) VALUES (1, 2, N'Apple', 20, 0.99, 19.8)
INSERT INTO [dbo].[OrderDetails] ([OrderDetails_Id], [Order_Id], [Product], [Quantity], [Unit_Price], [Extended_Price]) VALUES (2, 2, N'Banana', 25, 0.55, 13.75)
INSERT INTO [dbo].[OrderDetails] ([OrderDetails_Id], [Order_Id], [Product], [Quantity], [Unit_Price], [Extended_Price]) VALUES (3, 2, N'Grapes', 25, 1.55, 38.75)
INSERT INTO [dbo].[OrderDetails] ([OrderDetails_Id], [Order_Id], [Product], [Quantity], [Unit_Price], [Extended_Price]) VALUES (4, 2, N'Strawberries', 25, 0.99, 24.75)

SET IDENTITY_INSERT [dbo].[Orders] ON
INSERT INTO [dbo].[Orders] ([Order_Id], [Order_Date], [Employee], [Shipping_Address], [Ship_City], [Ship_State], [Zip], [Order_Total], [Tax], [Status], [Closed_Date]) VALUES (2, N'2017-04-29', N'Sam', N'132 AP drive', N'Clarksville', N'TN', 37043, 105.78, 8.73, N'New', N'2017-04-29')
SET IDENTITY_INSERT [dbo].[Orders] OFF

SET IDENTITY_INSERT [dbo].[OrderStatus] ON
INSERT INTO [dbo].[OrderStatus] ([OrderStatus_Id], [Status_Text]) VALUES (1, N'New')
INSERT INTO [dbo].[OrderStatus] ([OrderStatus_Id], [Status_Text]) VALUES (2, N'Invoiced')
INSERT INTO [dbo].[OrderStatus] ([OrderStatus_Id], [Status_Text]) VALUES (3, N'Shipped')
INSERT INTO [dbo].[OrderStatus] ([OrderStatus_Id], [Status_Text]) VALUES (4, N'Completed')
SET IDENTITY_INSERT [dbo].[OrderStatus] OFF

SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (6, N'CR001', N'Ravioli   ', 14.63, 19.5, 0, N'Pasta')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (7, N'CR002', N'Spaghetti ', 4.55, 8.99, 0, N'Pasta')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (8, N'CR003', N'Macaroni  ', 1.55, 4.55, 0, N'Pasta')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (9, N'BG001', N'Flour     ', 2.55, 3.99, 0, N'Baking')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (10, N'BG002', N'Sugar     ', 0.55, 2.99, 0, N'Baking')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (14, N'BG003', N'Vanilla Extract', 0.33, 1.55, 0, N'Baking')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (15, N'BG004', N'Baking Powder', 0.55, 2.99, 0, N'Baking')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (16, N'BD001', N'Dr.Pepsi', 0.55, 1.99, 0, N'Beverages')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (17, N'BD002', N'Nuka Cola', 0.55, 1.99, 0, N'Beverages')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (19, N'CD001', N'Reese''s', 0.25, 0.99, 0, N'Candy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (20, N'CD002', N'Smarties', 0.1, 0.55, 0, N'Candy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (22, N'CD003', N'Air Heads', 0.15, 0.55, 0, N'Candy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (23, N'4011', N'Banana', 0.1, 0.55, 0, N'Produce')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (24, N'4133', N'Apple', 0.15, 0.99, 0, N'Produce')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (25, N'4022', N'Grapes', 0.65, 1.55, 0, N'Produce')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (26, N'4028', N'Strawberries', 0.42, 0.99, 0, N'Produce')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (27, N'MD001', N'Steak', 0.78, 5.99, 0, N'Meat')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (28, N'MD002', N'Pork', 0.98, 3.56, 0, N'Meat')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (29, N'MD003', N'Chicken Thighs', 1.55, 3.55, 0, N'Meat')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (30, N'CB001', N'Admiral Crunch', 0.45, 1.99, 0, N'Cereal')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (31, N'CB002', N'Fruity Puffs', 0.45, 1.99, 0, N'Cereal')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (32, N'CB003', N'Tricks', 0.45, 1.99, 0, N'Cereal')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (33, N'CS001', N'Dorito''s', 0.46, 2.55, 0, N'Chips')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (34, N'CS002', N'Nacho''s', 0.25, 1.99, 0, N'Chips')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (35, N'CM001', N'Ketchup', 0.33, 0.99, 0, N'Condiments')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (36, N'CM002', N'Mustard', 0.38, 0.99, 0, N'Condiments')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (37, N'CM003', N'Ranch', 0.12, 0.99, 0, N'Condiments')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (38, N'DA001', N'Milk 2%', 0.15, 1.55, 0, N'Dairy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (40, N'DA002', N'Milk 1%', 0.15, 1.55, 0, N'Dairy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (41, N'DA003', N'Milk Skim', 0.15, 1.55, 0, N'Dairy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (42, N'DA004', N'Milk Whole', 0.15, 1.55, 0, N'Dairy')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (43, N'SP001', N'Ramen', 0.05, 0.55, 0, N'Soups')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (44, N'SP002', N'Chicken Noodle Soup', 0.25, 0.75, 0, N'Soups')
INSERT INTO [dbo].[Product] ([Product_Id], [Product_Code], [Product_Name], [Unit_Cost], [List_Price], [Discontinue], [Category]) VALUES (45, N'OL001', N'Olive Oil', 0.15, 1.99, 0, N'Oils')
SET IDENTITY_INSERT [dbo].[Product] OFF

SET IDENTITY_INSERT [dbo].[Product_Locations] ON
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (1, N'A101', 10, N'CR001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (2, N'A102', 10, N'CR002')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (3, N'A103', 10, N'CR003')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (4, N'A104', 15, N'BG001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (5, N'A105', 15, N'BG002')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (6, N'A106', 15, N'BG003')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (7, N'A107', 15, N'BG004')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (8, N'A108', 10, N'BD001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (9, N'A109', 10, N'BD002')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (10, N'A110', 10, N'CD001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (11, N'A111', 10, N'CD002')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (12, N'A112', 10, N'CD003')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (13, N'A113', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (14, N'A114', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (15, N'A115', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (16, N'A116', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (17, N'A117', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (18, N'A118', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (19, N'A119', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (20, N'A120', 50, N'4011')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (21, N'A121', 50, N'4133')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (22, N'A122', 50, N'4022')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (23, N'A123', 50, N'4028')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (24, N'A124', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (25, N'A125', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (26, N'A126', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (27, N'A127', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (28, N'A128', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (29, N'A129', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (30, N'A130', 15, N'MD001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (31, N'A131', 25, N'MD002')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (32, N'A132', 25, N'MD003')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (33, N'A133', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (34, N'A134', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (35, N'A135', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (36, N'A136', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (37, N'A137', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (38, N'A138', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (39, N'A139', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (40, N'A140', 20, N'CB001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (41, N'A141', 20, N'CB002')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (42, N'A142', 20, N'CB003')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (43, N'A143', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (44, N'A144', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (45, N'A145', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (46, N'A146', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (47, N'A147', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (48, N'A148', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (49, N'A149', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (50, N'A150', 15, N'CS001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (51, N'A151', 15, N'CS002')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (52, N'A152', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (53, N'A153', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (54, N'A154', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (55, N'A155', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (56, N'A156', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (57, N'A157', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (58, N'A158', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (59, N'A159', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (60, N'A160', 10, N'CM001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (61, N'A161', 10, N'CM002')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (62, N'A162', 10, N'CM003')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (63, N'A163', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (64, N'A164', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (65, N'A165', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (66, N'A166', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (67, N'A167', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (68, N'A168', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (69, N'A169', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (70, N'A170', 20, N'DA001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (71, N'A171', 20, N'DA002')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (72, N'A172', 20, N'DA003')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (73, N'A173', 20, N'DA004')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (74, N'A174', 50, N'DA005')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (75, N'A175', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (76, N'A176', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (77, N'A177', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (78, N'A178', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (79, N'A179', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (80, N'A180', 25, N'SP001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (81, N'A181', 25, N'SP002')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (82, N'A182', 10, N'OL001')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (83, N'A183', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (84, N'A184', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (85, N'A185', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (86, N'A186', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (87, N'A187', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (88, N'A188', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (89, N'A189', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (90, N'A190', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (91, N'A191', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (92, N'A192', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (93, N'A193', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (94, N'A194', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (95, N'A195', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (96, N'A196', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (97, N'A197', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (98, N'A198', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (99, N'A199', 0, N'Empty')
INSERT INTO [dbo].[Product_Locations] ([Locations_Id], [Product_Location], [Product_Quantity], [Product_Code]) VALUES (100, N'A200', 0, N'Empty')
SET IDENTITY_INSERT [dbo].[Product_Locations] OFF


SET IDENTITY_INSERT [dbo].[PurchaseOrderDetails] ON
INSERT INTO [dbo].[PurchaseOrderDetails] ([PurchaseOrderDetails_Id], [Purchase_Order_Number], [Product], [Quantity], [Unit_Price], [Extended_Price]) VALUES (4, 2, N'Millk 2%', 20, 0.15, 3)
INSERT INTO [dbo].[PurchaseOrderDetails] ([PurchaseOrderDetails_Id], [Purchase_Order_Number], [Product], [Quantity], [Unit_Price], [Extended_Price]) VALUES (5, 2, N'Milk Skim', 20, 0.15, 3)
INSERT INTO [dbo].[PurchaseOrderDetails] ([PurchaseOrderDetails_Id], [Purchase_Order_Number], [Product], [Quantity], [Unit_Price], [Extended_Price]) VALUES (7, 2, N'Eggs', 40, 0.55, 22)
SET IDENTITY_INSERT [dbo].[PurchaseOrderDetails] OFF

SET IDENTITY_INSERT [dbo].[PurchaseOrders] ON
INSERT INTO [dbo].[PurchaseOrders] ([PurchaseOrders_Id], [Order_Date], [Created_By], [Created_Date], [Shipping_Fee], [Tax], [Payment_Date], [Payment_Amount], [Order_Subtotal], [Order_Total], [Status], [Date_Received]) VALUES (2, N'2017-04-29', N'Bob', N'2017-04-29', 10, 2.52, N'2017-04-29', 40.52, 28, 40.52, N'New', N'2017-04-29')
SET IDENTITY_INSERT [dbo].[PurchaseOrders] OFF
