//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Customer
{
	private string company
	{
		get;
		set;
	}

	private string laseName
	{
		get;
		set;
	}

	private string firstName
	{
		get;
		set;
	}

	private string jobTilte
	{
		get;
		set;
	}

	private string address
	{
		get;
		set;
	}

	private string city
	{
		get;
		set;
	}

	private string state
	{
		get;
		set;
	}

	private object zip/PostalCode
	{
		get;
		set;
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

	public Customer()
	{
	}

}

