//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Employee
{
	private string firstName
	{
		get;
		set;
	}

	private string lastName
	{
		get;
		set;
	}

	private int employeeId
	{
		get;
		set;
	}

	private int employeeCode
	{
		get;
		set;
	}

	public virtual Login Login
	{
		get;
		set;
	}

	private Employee(string fn, string ln, int id, int employeeCode)
	{
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

}

